import type { Medicamento } from "./types";

export const medicamentos: Medicamento[] = [
  {
    slug: "dipirona-sodica",
    principioAtivo: "Dipirona Sódica",
    referencia: "Novalgina",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Dipirona Sódica EMS", fabricante: "EMS" },
      { nome: "Dipirona Sódica Medley", fabricante: "Medley" },
      { nome: "Dipirona Sódica Neo Química", fabricante: "Neo Química" },
      { nome: "Dipirona Sódica Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Analgésico e Antitérmico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 65,
    descricao: "Analgésico e antitérmico amplamente utilizado no Brasil para dores em geral e febre.",
  },
  {
    slug: "amoxicilina",
    principioAtivo: "Amoxicilina",
    referencia: "Amoxil",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Amoxicilina EMS", fabricante: "EMS" },
      { nome: "Amoxicilina Medley", fabricante: "Medley" },
      { nome: "Amoxicilina Teuto", fabricante: "Teuto" },
      { nome: "Amoxicilina Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Antibiótico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 70,
    descricao: "Antibiótico da classe das penicilinas indicado para diversas infecções bacterianas.",
  },
  {
    slug: "ibuprofeno",
    principioAtivo: "Ibuprofeno",
    referencia: "Advil",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Ibuprofeno EMS", fabricante: "EMS" },
      { nome: "Ibuprofeno Medley", fabricante: "Medley" },
      { nome: "Ibuprofeno Neo Química", fabricante: "Neo Química" },
      { nome: "Ibuprofeno Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Anti-inflamatório / Analgésico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 60,
    descricao: "Anti-inflamatório não esteroidal (AINE) indicado para dor, inflamação e febre.",
  },
  {
    slug: "paracetamol",
    principioAtivo: "Paracetamol (Acetaminofeno)",
    referencia: "Tylenol",
    fabricanteReferencia: "Kenvue (ex-Johnson & Johnson)",
    genericos: [
      { nome: "Paracetamol EMS", fabricante: "EMS" },
      { nome: "Paracetamol Medley", fabricante: "Medley" },
      { nome: "Paracetamol Prati", fabricante: "Prati-Donaduzzi" },
      { nome: "Paracetamol Farmacêutico Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Analgésico e Antitérmico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 62,
    descricao: "Analgésico e antitérmico de amplo uso, indicado para dores leves a moderadas e febre.",
  },
  {
    slug: "omeprazol",
    principioAtivo: "Omeprazol",
    referencia: "Losec",
    fabricanteReferencia: "AstraZeneca",
    genericos: [
      { nome: "Omeprazol EMS", fabricante: "EMS" },
      { nome: "Omeprazol Medley", fabricante: "Medley" },
      { nome: "Omeprazol Eurofarma", fabricante: "Eurofarma" },
      { nome: "Omeprazol Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Inibidor de Bomba de Prótons",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 75,
    descricao: "Inibidor da bomba de prótons usado no tratamento de úlceras gástricas e refluxo.",
  },
  {
    slug: "atenolol",
    principioAtivo: "Atenolol",
    referencia: "Tenormin",
    fabricanteReferencia: "AstraZeneca",
    genericos: [
      { nome: "Atenolol EMS", fabricante: "EMS" },
      { nome: "Atenolol Medley", fabricante: "Medley" },
      { nome: "Atenolol Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Beta-bloqueador / Cardiovascular",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 68,
    descricao: "Beta-bloqueador utilizado no tratamento de hipertensão arterial e angina.",
  },
  {
    slug: "losartana-potassica",
    principioAtivo: "Losartana Potássica",
    referencia: "Cozaar",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Losartana Potássica EMS", fabricante: "EMS" },
      { nome: "Losartana Potássica Medley", fabricante: "Medley" },
      { nome: "Losartana Potássica Eurofarma", fabricante: "Eurofarma" },
      { nome: "Losartana Potássica Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Anti-hipertensivo / ARA II",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 72,
    descricao: "Antagonista dos receptores da angiotensina II (ARA II) para tratamento de hipertensão.",
  },
  {
    slug: "metformina",
    principioAtivo: "Cloridrato de Metformina",
    referencia: "Glifage",
    fabricanteReferencia: "Merck",
    genericos: [
      { nome: "Metformina EMS", fabricante: "EMS" },
      { nome: "Metformina Medley", fabricante: "Medley" },
      { nome: "Metformina Neo Química", fabricante: "Neo Química" },
      { nome: "Metformina Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antidiabético / Biguanida",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 78,
    descricao: "Antidiabético oral de primeira linha para diabetes tipo 2, reduz glicose sanguínea.",
  },
  {
    slug: "enalapril",
    principioAtivo: "Maleato de Enalapril",
    referencia: "Renitec",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Enalapril EMS", fabricante: "EMS" },
      { nome: "Enalapril Medley", fabricante: "Medley" },
      { nome: "Enalapril Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Anti-hipertensivo / IECA",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 70,
    descricao: "Inibidor da enzima conversora de angiotensina (IECA) indicado para hipertensão e insuficiência cardíaca.",
  },
  {
    slug: "sinvastatina",
    principioAtivo: "Sinvastatina",
    referencia: "Zocor",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Sinvastatina EMS", fabricante: "EMS" },
      { nome: "Sinvastatina Medley", fabricante: "Medley" },
      { nome: "Sinvastatina Eurofarma", fabricante: "Eurofarma" },
      { nome: "Sinvastatina Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Hipolipemiante / Estatina",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 73,
    descricao: "Estatina utilizada para redução do colesterol LDL e prevenção cardiovascular.",
  },
  {
    slug: "azitromicina",
    principioAtivo: "Azitromicina Di-hidratada",
    referencia: "Zithromax",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Azitromicina EMS", fabricante: "EMS" },
      { nome: "Azitromicina Medley", fabricante: "Medley" },
      { nome: "Azitromicina Sandoz", fabricante: "Sandoz" },
      { nome: "Azitromicina Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antibiótico / Macrolídeo",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 67,
    descricao: "Antibiótico macrolídeo de curta duração para infecções respiratórias e de pele.",
  },
  {
    slug: "cetirizina",
    principioAtivo: "Cloridrato de Cetirizina",
    referencia: "Zyrtec",
    fabricanteReferencia: "UCB",
    genericos: [
      { nome: "Cetirizina EMS", fabricante: "EMS" },
      { nome: "Cetirizina Medley", fabricante: "Medley" },
      { nome: "Cetirizina Neo Química", fabricante: "Neo Química" },
    ],
    classeTerapeutica: "Anti-histamínico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 71,
    descricao: "Anti-histamínico de segunda geração para alergias, rinite alérgica e urticária.",
  },
  {
    slug: "loratadina",
    principioAtivo: "Loratadina",
    referencia: "Claritin",
    fabricanteReferencia: "Bayer",
    genericos: [
      { nome: "Loratadina EMS", fabricante: "EMS" },
      { nome: "Loratadina Medley", fabricante: "Medley" },
      { nome: "Loratadina Prati", fabricante: "Prati-Donaduzzi" },
      { nome: "Loratadina Neo Química", fabricante: "Neo Química" },
    ],
    classeTerapeutica: "Anti-histamínico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 69,
    descricao: "Anti-histamínico não sedante indicado para rinite alérgica e alergias de pele.",
  },
  {
    slug: "fluconazol",
    principioAtivo: "Fluconazol",
    referencia: "Diflucan",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Fluconazol EMS", fabricante: "EMS" },
      { nome: "Fluconazol Medley", fabricante: "Medley" },
      { nome: "Fluconazol Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antifúngico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 64,
    descricao: "Antifúngico triazólico eficaz contra candidíase e outras infecções fúngicas.",
  },
  {
    slug: "ciprofloxacino",
    principioAtivo: "Cloridrato de Ciprofloxacino",
    referencia: "Cipro",
    fabricanteReferencia: "Bayer",
    genericos: [
      { nome: "Ciprofloxacino EMS", fabricante: "EMS" },
      { nome: "Ciprofloxacino Medley", fabricante: "Medley" },
      { nome: "Ciprofloxacino Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Antibiótico / Fluoroquinolona",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 66,
    descricao: "Antibiótico fluoroquinolônico de amplo espectro para infecções urinárias e respiratórias.",
  },
  {
    slug: "prednisona",
    principioAtivo: "Prednisona",
    referencia: "Meticorten",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Prednisona EMS", fabricante: "EMS" },
      { nome: "Prednisona Medley", fabricante: "Medley" },
      { nome: "Prednisona Neo Química", fabricante: "Neo Química" },
    ],
    classeTerapeutica: "Corticosteroide",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 63,
    descricao: "Corticosteroide oral utilizado para processos inflamatórios e doenças autoimunes.",
  },
  {
    slug: "dexametasona",
    principioAtivo: "Dexametasona",
    referencia: "Decadron",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Dexametasona EMS", fabricante: "EMS" },
      { nome: "Dexametasona Medley", fabricante: "Medley" },
      { nome: "Dexametasona Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Corticosteroide",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 68,
    descricao: "Corticosteroide de alta potência para inflamações graves e alergias severas.",
  },
  {
    slug: "pantoprazol",
    principioAtivo: "Pantoprazol Sódico",
    referencia: "Pantozol",
    fabricanteReferencia: "Takeda",
    genericos: [
      { nome: "Pantoprazol EMS", fabricante: "EMS" },
      { nome: "Pantoprazol Medley", fabricante: "Medley" },
      { nome: "Pantoprazol Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Inibidor de Bomba de Prótons",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 74,
    descricao: "Inibidor da bomba de prótons indicado para DRGE, úlceras e síndrome de Zollinger-Ellison.",
  },
  {
    slug: "esomeprazol",
    principioAtivo: "Esomeprazol Magnésico",
    referencia: "Nexium",
    fabricanteReferencia: "AstraZeneca",
    genericos: [
      { nome: "Esomeprazol EMS", fabricante: "EMS" },
      { nome: "Esomeprazol Medley", fabricante: "Medley" },
      { nome: "Esomeprazol Teuto", fabricante: "Teuto" },
    ],
    classeTerapeutica: "Inibidor de Bomba de Prótons",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 76,
    descricao: "IBP de segunda geração para tratamento de esofagite erosiva e refluxo gastroesofágico.",
  },
  {
    slug: "lansoprazol",
    principioAtivo: "Lansoprazol",
    referencia: "Prazol",
    fabricanteReferencia: "Abbott",
    genericos: [
      { nome: "Lansoprazol EMS", fabricante: "EMS" },
      { nome: "Lansoprazol Medley", fabricante: "Medley" },
      { nome: "Lansoprazol Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Inibidor de Bomba de Prótons",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 72,
    descricao: "Inibidor da bomba de prótons para úlceras gástricas, duodenais e erradicação de H. pylori.",
  },
  {
    slug: "clonazepam",
    principioAtivo: "Clonazepam",
    referencia: "Rivotril",
    fabricanteReferencia: "Roche",
    genericos: [
      { nome: "Clonazepam EMS", fabricante: "EMS" },
      { nome: "Clonazepam Medley", fabricante: "Medley" },
      { nome: "Clonazepam Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Benzodiazepínico / Anticonvulsivante",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 58,
    descricao: "Benzodiazepínico utilizado no tratamento de epilepsia, ansiedade e transtorno do pânico.",
  },
  {
    slug: "alprazolam",
    principioAtivo: "Alprazolam",
    referencia: "Frontal",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Alprazolam EMS", fabricante: "EMS" },
      { nome: "Alprazolam Medley", fabricante: "Medley" },
      { nome: "Alprazolam Teuto", fabricante: "Teuto" },
    ],
    classeTerapeutica: "Benzodiazepínico / Ansiolítico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 55,
    descricao: "Benzodiazepínico indicado para transtornos de ansiedade e síndrome do pânico.",
  },
  {
    slug: "fluoxetina",
    principioAtivo: "Cloridrato de Fluoxetina",
    referencia: "Prozac",
    fabricanteReferencia: "Lilly",
    genericos: [
      { nome: "Fluoxetina EMS", fabricante: "EMS" },
      { nome: "Fluoxetina Medley", fabricante: "Medley" },
      { nome: "Fluoxetina Neo Química", fabricante: "Neo Química" },
      { nome: "Fluoxetina Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antidepressivo / ISRS",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 77,
    descricao: "Antidepressivo ISRS de primeira linha para depressão, TOC e bulimia nervosa.",
  },
  {
    slug: "sertralina",
    principioAtivo: "Cloridrato de Sertralina",
    referencia: "Zoloft",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Sertralina EMS", fabricante: "EMS" },
      { nome: "Sertralina Medley", fabricante: "Medley" },
      { nome: "Sertralina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antidepressivo / ISRS",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 74,
    descricao: "Antidepressivo ISRS utilizado para depressão, ansiedade social e PTSD.",
  },
  {
    slug: "amitriptilina",
    principioAtivo: "Cloridrato de Amitriptilina",
    referencia: "Tryptanol",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Amitriptilina EMS", fabricante: "EMS" },
      { nome: "Amitriptilina Medley", fabricante: "Medley" },
      { nome: "Amitriptilina Teuto", fabricante: "Teuto" },
    ],
    classeTerapeutica: "Antidepressivo Tricíclico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 65,
    descricao: "Antidepressivo tricíclico indicado para depressão, dor neuropática e enxaqueca.",
  },
  {
    slug: "metoclopramida",
    principioAtivo: "Cloridrato de Metoclopramida",
    referencia: "Plasil",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Metoclopramida EMS", fabricante: "EMS" },
      { nome: "Metoclopramida Medley", fabricante: "Medley" },
      { nome: "Metoclopramida Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antiemético / Procinético",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 60,
    descricao: "Antiemético e procinético para náuseas, vômitos e gastroparesia.",
  },
  {
    slug: "domperidona",
    principioAtivo: "Domperidona",
    referencia: "Motilium",
    fabricanteReferencia: "Janssen",
    genericos: [
      { nome: "Domperidona EMS", fabricante: "EMS" },
      { nome: "Domperidona Medley", fabricante: "Medley" },
      { nome: "Domperidona Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antiemético / Procinético",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 62,
    descricao: "Procinético indicado para náuseas, vômitos e desconforto gástrico funcional.",
  },
  {
    slug: "ondansetrona",
    principioAtivo: "Cloridrato de Ondansetrona",
    referencia: "Zofran",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Ondansetrona EMS", fabricante: "EMS" },
      { nome: "Ondansetrona Medley", fabricante: "Medley" },
      { nome: "Ondansetrona Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Antiemético / Antagonista 5-HT3",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 71,
    descricao: "Antiemético potente utilizado para náuseas e vômitos por quimioterapia e cirurgias.",
  },
  {
    slug: "loperamida",
    principioAtivo: "Cloridrato de Loperamida",
    referencia: "Imosec",
    fabricanteReferencia: "Janssen",
    genericos: [
      { nome: "Loperamida EMS", fabricante: "EMS" },
      { nome: "Loperamida Medley", fabricante: "Medley" },
      { nome: "Loperamida Neo Química", fabricante: "Neo Química" },
    ],
    classeTerapeutica: "Antidiarreico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 58,
    descricao: "Antidiarreico opioide periférico para controle de diarreia aguda e crônica.",
  },
  {
    slug: "metronidazol",
    principioAtivo: "Metronidazol",
    referencia: "Flagyl",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Metronidazol EMS", fabricante: "EMS" },
      { nome: "Metronidazol Medley", fabricante: "Medley" },
      { nome: "Metronidazol Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antibiótico / Antiprotozoário",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 66,
    descricao: "Antibiótico e antiprotozoário eficaz contra Giardia, amebíase e infecções anaeróbicas.",
  },
  {
    slug: "doxiciclina",
    principioAtivo: "Cloridrato de Doxiciclina",
    referencia: "Vibramicina",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Doxiciclina EMS", fabricante: "EMS" },
      { nome: "Doxiciclina Medley", fabricante: "Medley" },
      { nome: "Doxiciclina Teuto", fabricante: "Teuto" },
    ],
    classeTerapeutica: "Antibiótico / Tetraciclina",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 64,
    descricao: "Antibiótico tetraciclínico para infecções respiratórias, acne e ISTs.",
  },
  {
    slug: "clindamicina",
    principioAtivo: "Cloridrato de Clindamicina",
    referencia: "Dalacin",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Clindamicina EMS", fabricante: "EMS" },
      { nome: "Clindamicina Medley", fabricante: "Medley" },
      { nome: "Clindamicina Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Antibiótico / Lincosamida",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 61,
    descricao: "Antibiótico lincosamida eficaz para infecções de pele e tecidos moles, acne.",
  },
  {
    slug: "amoxicilina-clavulanato",
    principioAtivo: "Amoxicilina + Clavulanato de Potássio",
    referencia: "Clavulin",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Amoxicilina+Clavulanato EMS", fabricante: "EMS" },
      { nome: "Amoxicilina+Clavulanato Medley", fabricante: "Medley" },
      { nome: "Amoxicilina+Clavulanato Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Antibiótico / Penicilina + Inibidor de Beta-lactamase",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 55,
    descricao: "Associação de antibiótico com inibidor de beta-lactamase para infecções resistentes.",
  },
  {
    slug: "betaistina",
    principioAtivo: "Cloridrato de Betaistina",
    referencia: "Betaserc",
    fabricanteReferencia: "Abbott",
    genericos: [
      { nome: "Betaistina EMS", fabricante: "EMS" },
      { nome: "Betaistina Medley", fabricante: "Medley" },
      { nome: "Betaistina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antivertiginoso",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 67,
    descricao: "Antivertiginoso indicado para doença de Ménière, tontura e vertigem.",
  },
  {
    slug: "salbutamol",
    principioAtivo: "Sulfato de Salbutamol",
    referencia: "Aerolin",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Salbutamol EMS", fabricante: "EMS" },
      { nome: "Salbutamol Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Broncodilatador / Beta-2 agonista",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 50,
    descricao: "Broncodilatador de ação rápida para tratamento e prevenção de broncoespasmo na asma.",
  },
  {
    slug: "budesonida",
    principioAtivo: "Budesonida",
    referencia: "Pulmicort",
    fabricanteReferencia: "AstraZeneca",
    genericos: [
      { nome: "Budesonida EMS", fabricante: "EMS" },
      { nome: "Budesonida Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Corticosteroide Inalatório",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 52,
    descricao: "Corticosteroide inalatório para controle da asma e rinite alérgica.",
  },
  {
    slug: "montelucaste",
    principioAtivo: "Montelucaste Sódico",
    referencia: "Singulair",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Montelucaste EMS", fabricante: "EMS" },
      { nome: "Montelucaste Medley", fabricante: "Medley" },
      { nome: "Montelucaste Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Antiasmático / Antagonista de Leucotrienos",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 73,
    descricao: "Antagonista de receptores de leucotrienos para profilaxia e tratamento crônico da asma.",
  },
  {
    slug: "captopril",
    principioAtivo: "Captopril",
    referencia: "Capoten",
    fabricanteReferencia: "Bristol-Myers Squibb",
    genericos: [
      { nome: "Captopril EMS", fabricante: "EMS" },
      { nome: "Captopril Medley", fabricante: "Medley" },
      { nome: "Captopril Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Anti-hipertensivo / IECA",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 76,
    descricao: "Inibidor da ECA de ação curta para hipertensão arterial e insuficiência cardíaca.",
  },
  {
    slug: "hidroclorotiazida",
    principioAtivo: "Hidroclorotiazida",
    referencia: "Clorana",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Hidroclorotiazida EMS", fabricante: "EMS" },
      { nome: "Hidroclorotiazida Medley", fabricante: "Medley" },
      { nome: "Hidroclorotiazida Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Diurético Tiazídico / Anti-hipertensivo",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 74,
    descricao: "Diurético tiazídico para hipertensão arterial e edema por retenção de líquidos.",
  },
  {
    slug: "furosemida",
    principioAtivo: "Furosemida",
    referencia: "Lasix",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Furosemida EMS", fabricante: "EMS" },
      { nome: "Furosemida Medley", fabricante: "Medley" },
      { nome: "Furosemida Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Diurético de Alça",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 72,
    descricao: "Diurético de alça potente indicado para edema, hipertensão e insuficiência cardíaca.",
  },
  {
    slug: "espironolactona",
    principioAtivo: "Espironolactona",
    referencia: "Aldactone",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Espironolactona EMS", fabricante: "EMS" },
      { nome: "Espironolactona Medley", fabricante: "Medley" },
      { nome: "Espironolactona Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Diurético Poupador de Potássio / Anti-aldosterônico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 65,
    descricao: "Diurético antagonista da aldosterona para hipertensão, edema e insuficiência cardíaca.",
  },
  {
    slug: "anlodipino",
    principioAtivo: "Besilato de Anlodipino",
    referencia: "Norvasc",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Anlodipino EMS", fabricante: "EMS" },
      { nome: "Anlodipino Medley", fabricante: "Medley" },
      { nome: "Anlodipino Sandoz", fabricante: "Sandoz" },
      { nome: "Anlodipino Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Bloqueador de Canais de Cálcio / Anti-hipertensivo",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 79,
    descricao: "Bloqueador de canais de cálcio de longa ação para hipertensão e angina estável.",
  },
  {
    slug: "carvedilol",
    principioAtivo: "Carvedilol",
    referencia: "Coreg",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Carvedilol EMS", fabricante: "EMS" },
      { nome: "Carvedilol Medley", fabricante: "Medley" },
      { nome: "Carvedilol Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Beta-bloqueador Não-seletivo / Cardiovascular",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 70,
    descricao: "Beta-bloqueador com atividade alfa-1 indicado para insuficiência cardíaca e hipertensão.",
  },
  {
    slug: "propranolol",
    principioAtivo: "Cloridrato de Propranolol",
    referencia: "Inderal",
    fabricanteReferencia: "AstraZeneca",
    genericos: [
      { nome: "Propranolol EMS", fabricante: "EMS" },
      { nome: "Propranolol Medley", fabricante: "Medley" },
      { nome: "Propranolol Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Beta-bloqueador / Cardiovascular",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 73,
    descricao: "Beta-bloqueador não seletivo para hipertensão, arritmias, angina e profilaxia de enxaqueca.",
  },
  {
    slug: "metoprolol",
    principioAtivo: "Succinato de Metoprolol",
    referencia: "Seloken",
    fabricanteReferencia: "AstraZeneca",
    genericos: [
      { nome: "Metoprolol EMS", fabricante: "EMS" },
      { nome: "Metoprolol Medley", fabricante: "Medley" },
      { nome: "Metoprolol Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Beta-bloqueador Seletivo / Cardiovascular",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 68,
    descricao: "Beta-1 seletivo de liberação prolongada para hipertensão, angina e insuficiência cardíaca.",
  },
  {
    slug: "rosuvastatina",
    principioAtivo: "Rosuvastatina Cálcica",
    referencia: "Crestor",
    fabricanteReferencia: "AstraZeneca",
    genericos: [
      { nome: "Rosuvastatina EMS", fabricante: "EMS" },
      { nome: "Rosuvastatina Medley", fabricante: "Medley" },
      { nome: "Rosuvastatina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Hipolipemiante / Estatina",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 75,
    descricao: "Estatina de alta potência para redução de LDL e prevenção de eventos cardiovasculares.",
  },
  {
    slug: "atorvastatina",
    principioAtivo: "Atorvastatina Cálcica",
    referencia: "Lipitor",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Atorvastatina EMS", fabricante: "EMS" },
      { nome: "Atorvastatina Medley", fabricante: "Medley" },
      { nome: "Atorvastatina Sandoz", fabricante: "Sandoz" },
      { nome: "Atorvastatina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Hipolipemiante / Estatina",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 78,
    descricao: "Uma das estatinas mais prescritas mundialmente para controle do colesterol e triglicerídeos.",
  },
  {
    slug: "clopidogrel",
    principioAtivo: "Bissulfato de Clopidogrel",
    referencia: "Plavix",
    fabricanteReferencia: "Sanofi / BMS",
    genericos: [
      { nome: "Clopidogrel EMS", fabricante: "EMS" },
      { nome: "Clopidogrel Medley", fabricante: "Medley" },
      { nome: "Clopidogrel Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antiagregante Plaquetário",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 72,
    descricao: "Antiagregante plaquetário para prevenção de AVC, infarto e trombose em stent.",
  },
  {
    slug: "acido-acetilsalicilico",
    principioAtivo: "Ácido Acetilsalicílico (AAS)",
    referencia: "Aspirina",
    fabricanteReferencia: "Bayer",
    genericos: [
      { nome: "AAS EMS", fabricante: "EMS" },
      { nome: "AAS Medley", fabricante: "Medley" },
      { nome: "AAS Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antiagregante / Analgésico / AINE",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 60,
    descricao: "Usado como analgésico, antipirético, anti-inflamatório e antiagregante plaquetário.",
  },
  {
    slug: "levotiroxina",
    principioAtivo: "Levotiroxina Sódica",
    referencia: "Puran T4",
    fabricanteReferencia: "Abbott",
    genericos: [
      { nome: "Levotiroxina EMS", fabricante: "EMS" },
      { nome: "Levotiroxina Medley", fabricante: "Medley" },
      { nome: "Levotiroxina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Hormônio Tireoidiano",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 55,
    descricao: "Reposição hormonal tireoidiana para hipotireoidismo e tireoidite de Hashimoto.",
  },
  {
    slug: "glibenclamida",
    principioAtivo: "Glibenclamida",
    referencia: "Daonil",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Glibenclamida EMS", fabricante: "EMS" },
      { nome: "Glibenclamida Medley", fabricante: "Medley" },
      { nome: "Glibenclamida Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antidiabético / Sulfonilureia",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 70,
    descricao: "Sulfonilureia de primeira geração para diabetes tipo 2, estimula secreção de insulina.",
  },
  {
    slug: "alopurinol",
    principioAtivo: "Alopurinol",
    referencia: "Zyloric",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Alopurinol EMS", fabricante: "EMS" },
      { nome: "Alopurinol Medley", fabricante: "Medley" },
      { nome: "Alopurinol Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antigotoso / Inibidor da Xantina Oxidase",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 69,
    descricao: "Inibidor da xantina oxidase para tratamento e prevenção de gota e urolitíase úrica.",
  },
  {
    slug: "diclofenaco-sodico",
    principioAtivo: "Diclofenaco Sódico",
    referencia: "Cataflam / Voltaren",
    fabricanteReferencia: "Novartis",
    genericos: [
      { nome: "Diclofenaco Sódico EMS", fabricante: "EMS" },
      { nome: "Diclofenaco Sódico Medley", fabricante: "Medley" },
      { nome: "Diclofenaco Sódico Prati", fabricante: "Prati-Donaduzzi" },
      { nome: "Diclofenaco Sódico Neo Química", fabricante: "Neo Química" },
    ],
    classeTerapeutica: "Anti-inflamatório Não Esteroidal (AINE)",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 67,
    descricao: "AINE potente para dores musculoesqueléticas, artrite reumatoide e dismenorreia.",
  },
  {
    slug: "naproxeno",
    principioAtivo: "Naproxeno Sódico",
    referencia: "Flanax",
    fabricanteReferencia: "Bayer",
    genericos: [
      { nome: "Naproxeno Sódico EMS", fabricante: "EMS" },
      { nome: "Naproxeno Sódico Medley", fabricante: "Medley" },
      { nome: "Naproxeno Sódico Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Anti-inflamatório Não Esteroidal (AINE)",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 63,
    descricao: "AINE de ação prolongada para dores reumáticas, musculares e cólicas menstruais.",
  },
  {
    slug: "meloxicam",
    principioAtivo: "Meloxicam",
    referencia: "Mobic",
    fabricanteReferencia: "Boehringer Ingelheim",
    genericos: [
      { nome: "Meloxicam EMS", fabricante: "EMS" },
      { nome: "Meloxicam Medley", fabricante: "Medley" },
      { nome: "Meloxicam Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Anti-inflamatório Seletivo COX-2 / AINE",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 65,
    descricao: "AINE com seletividade relativa para COX-2, indicado para artrite reumatoide e osteoartrose.",
  },
  {
    slug: "tramadol",
    principioAtivo: "Cloridrato de Tramadol",
    referencia: "Tramal",
    fabricanteReferencia: "Mundipharma",
    genericos: [
      { nome: "Tramadol EMS", fabricante: "EMS" },
      { nome: "Tramadol Medley", fabricante: "Medley" },
      { nome: "Tramadol Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Analgésico Opioide",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 58,
    descricao: "Opioide de ação central para dores moderadas a severas, incluindo dor neuropática.",
  },
  {
    slug: "pregabalina",
    principioAtivo: "Pregabalina",
    referencia: "Lyrica",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Pregabalina EMS", fabricante: "EMS" },
      { nome: "Pregabalina Medley", fabricante: "Medley" },
      { nome: "Pregabalina Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Anticonvulsivante / Dor Neuropática",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 71,
    descricao: "Anticonvulsivante gabapentinoide para dor neuropática, fibromialgia e epilepsia.",
  },
  {
    slug: "gabapentina",
    principioAtivo: "Gabapentina",
    referencia: "Neurontin",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Gabapentina EMS", fabricante: "EMS" },
      { nome: "Gabapentina Medley", fabricante: "Medley" },
      { nome: "Gabapentina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Anticonvulsivante / Dor Neuropática",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 69,
    descricao: "Anticonvulsivante para epilepsia, neuralgia pós-herpética e dor neuropática.",
  },
  {
    slug: "topiramato",
    principioAtivo: "Topiramato",
    referencia: "Topamax",
    fabricanteReferencia: "Janssen",
    genericos: [
      { nome: "Topiramato EMS", fabricante: "EMS" },
      { nome: "Topiramato Medley", fabricante: "Medley" },
      { nome: "Topiramato Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Anticonvulsivante",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 72,
    descricao: "Anticonvulsivante de amplo espectro para epilepsia e profilaxia de enxaqueca.",
  },
  {
    slug: "carbamazepina",
    principioAtivo: "Carbamazepina",
    referencia: "Tegretol",
    fabricanteReferencia: "Novartis",
    genericos: [
      { nome: "Carbamazepina EMS", fabricante: "EMS" },
      { nome: "Carbamazepina Medley", fabricante: "Medley" },
      { nome: "Carbamazepina Neo Química", fabricante: "Neo Química" },
    ],
    classeTerapeutica: "Anticonvulsivante / Estabilizador de Humor",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 67,
    descricao: "Anticonvulsivante e estabilizador de humor para epilepsia, neuralgia do trigêmeo e transtorno bipolar.",
  },
  {
    slug: "levetiracetam",
    principioAtivo: "Levetiracetam",
    referencia: "Keppra",
    fabricanteReferencia: "UCB",
    genericos: [
      { nome: "Levetiracetam EMS", fabricante: "EMS" },
      { nome: "Levetiracetam Medley", fabricante: "Medley" },
      { nome: "Levetiracetam Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Anticonvulsivante",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 74,
    descricao: "Anticonvulsivante de nova geração para convulsões parciais e tônico-clônicas generalizadas.",
  },
  {
    slug: "valproato-de-sodio",
    principioAtivo: "Valproato de Sódio / Ácido Valpróico",
    referencia: "Depakote",
    fabricanteReferencia: "Abbott",
    genericos: [
      { nome: "Valproato EMS", fabricante: "EMS" },
      { nome: "Valproato Medley", fabricante: "Medley" },
      { nome: "Valproato Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Anticonvulsivante / Estabilizador de Humor",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 65,
    descricao: "Anticonvulsivante e estabilizador de humor para epilepsia e transtorno bipolar.",
  },
  {
    slug: "haloperidol",
    principioAtivo: "Haloperidol",
    referencia: "Haldol",
    fabricanteReferencia: "Janssen",
    genericos: [
      { nome: "Haloperidol EMS", fabricante: "EMS" },
      { nome: "Haloperidol Medley", fabricante: "Medley" },
      { nome: "Haloperidol Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antipsicótico / Neuroléptico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 64,
    descricao: "Antipsicótico típico para esquizofrenia, psicoses agudas e síndrome de Tourette.",
  },
  {
    slug: "risperidona",
    principioAtivo: "Risperidona",
    referencia: "Risperdal",
    fabricanteReferencia: "Janssen",
    genericos: [
      { nome: "Risperidona EMS", fabricante: "EMS" },
      { nome: "Risperidona Medley", fabricante: "Medley" },
      { nome: "Risperidona Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antipsicótico Atípico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 72,
    descricao: "Antipsicótico atípico para esquizofrenia, transtorno bipolar e irritabilidade no autismo.",
  },
  {
    slug: "quetiapina",
    principioAtivo: "Fumarato de Quetiapina",
    referencia: "Seroquel",
    fabricanteReferencia: "AstraZeneca",
    genericos: [
      { nome: "Quetiapina EMS", fabricante: "EMS" },
      { nome: "Quetiapina Medley", fabricante: "Medley" },
      { nome: "Quetiapina Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Antipsicótico Atípico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 74,
    descricao: "Antipsicótico atípico para esquizofrenia, episódios maníacos bipolares e depressão bipolar.",
  },
  {
    slug: "olanzapina",
    principioAtivo: "Olanzapina",
    referencia: "Zyprexa",
    fabricanteReferencia: "Lilly",
    genericos: [
      { nome: "Olanzapina EMS", fabricante: "EMS" },
      { nome: "Olanzapina Medley", fabricante: "Medley" },
      { nome: "Olanzapina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antipsicótico Atípico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 76,
    descricao: "Antipsicótico atípico para esquizofrenia e episódios maníacos do transtorno bipolar.",
  },
  {
    slug: "donepezila",
    principioAtivo: "Cloridrato de Donepezila",
    referencia: "Aricept",
    fabricanteReferencia: "Pfizer / Eisai",
    genericos: [
      { nome: "Donepezila EMS", fabricante: "EMS" },
      { nome: "Donepezila Medley", fabricante: "Medley" },
      { nome: "Donepezila Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Anticolinesterásico / Doença de Alzheimer",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 70,
    descricao: "Inibidor da acetilcolinesterase para tratamento da doença de Alzheimer leve a moderada.",
  },
  {
    slug: "metilfenidato",
    principioAtivo: "Cloridrato de Metilfenidato",
    referencia: "Ritalina",
    fabricanteReferencia: "Novartis",
    genericos: [
      { nome: "Metilfenidato EMS", fabricante: "EMS" },
      { nome: "Metilfenidato Medley", fabricante: "Medley" },
      { nome: "Metilfenidato Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Psicoestimulante / TDAH",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 53,
    descricao: "Estimulante do SNC indicado para TDAH em crianças, adolescentes e adultos.",
  },
  {
    slug: "bupropiona",
    principioAtivo: "Cloridrato de Bupropiona",
    referencia: "Wellbutrin / Zyban",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Bupropiona EMS", fabricante: "EMS" },
      { nome: "Bupropiona Medley", fabricante: "Medley" },
      { nome: "Bupropiona Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antidepressivo / Auxiliar no Tabagismo",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 68,
    descricao: "Antidepressivo atípico utilizado para depressão e cessação do tabagismo.",
  },
  {
    slug: "venlafaxina",
    principioAtivo: "Cloridrato de Venlafaxina",
    referencia: "Efexor",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Venlafaxina EMS", fabricante: "EMS" },
      { nome: "Venlafaxina Medley", fabricante: "Medley" },
      { nome: "Venlafaxina Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Antidepressivo / IRSN",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 72,
    descricao: "Inibidor da recaptação de serotonina e noradrenalina (IRSN) para depressão e ansiedade.",
  },
  {
    slug: "escitalopram",
    principioAtivo: "Oxalato de Escitalopram",
    referencia: "Lexapro",
    fabricanteReferencia: "Lundbeck",
    genericos: [
      { nome: "Escitalopram EMS", fabricante: "EMS" },
      { nome: "Escitalopram Medley", fabricante: "Medley" },
      { nome: "Escitalopram Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antidepressivo / ISRS",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 73,
    descricao: "ISRS altamente seletivo para depressão maior, transtorno de ansiedade generalizada e pânico.",
  },
  {
    slug: "paroxetina",
    principioAtivo: "Cloridrato de Paroxetina",
    referencia: "Aropax",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Paroxetina EMS", fabricante: "EMS" },
      { nome: "Paroxetina Medley", fabricante: "Medley" },
      { nome: "Paroxetina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antidepressivo / ISRS",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 71,
    descricao: "ISRS para depressão, transtorno obsessivo-compulsivo, fobia social e transtorno do pânico.",
  },
  {
    slug: "zolpidem",
    principioAtivo: "Tartarato de Zolpidem",
    referencia: "Stilnox",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Zolpidem EMS", fabricante: "EMS" },
      { nome: "Zolpidem Medley", fabricante: "Medley" },
      { nome: "Zolpidem Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Hipnótico / Indução do Sono",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 57,
    descricao: "Hipnótico imidazopiridínico para tratamento de curto prazo da insônia.",
  },
  {
    slug: "bromazepam",
    principioAtivo: "Bromazepam",
    referencia: "Lexotan",
    fabricanteReferencia: "Roche",
    genericos: [
      { nome: "Bromazepam EMS", fabricante: "EMS" },
      { nome: "Bromazepam Medley", fabricante: "Medley" },
      { nome: "Bromazepam Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Benzodiazepínico / Ansiolítico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 55,
    descricao: "Benzodiazepínico de potência intermediária para ansiedade generalizada e tensão.",
  },
  {
    slug: "diazepam",
    principioAtivo: "Diazepam",
    referencia: "Valium",
    fabricanteReferencia: "Roche",
    genericos: [
      { nome: "Diazepam EMS", fabricante: "EMS" },
      { nome: "Diazepam Medley", fabricante: "Medley" },
      { nome: "Diazepam Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Benzodiazepínico / Ansiolítico / Miorrelaxante",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 62,
    descricao: "Benzodiazepínico clássico para ansiedade, espasmos musculares, convulsões e abstinência alcoólica.",
  },
  {
    slug: "nifedipino",
    principioAtivo: "Nifedipino",
    referencia: "Adalat",
    fabricanteReferencia: "Bayer",
    genericos: [
      { nome: "Nifedipino EMS", fabricante: "EMS" },
      { nome: "Nifedipino Medley", fabricante: "Medley" },
      { nome: "Nifedipino Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Bloqueador de Canais de Cálcio / Anti-hipertensivo",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 70,
    descricao: "Bloqueador de canal de cálcio diidropiridínico para hipertensão arterial e angina.",
  },
  {
    slug: "finasterida",
    principioAtivo: "Finasterida",
    referencia: "Proscar / Propecia",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Finasterida EMS", fabricante: "EMS" },
      { nome: "Finasterida Medley", fabricante: "Medley" },
      { nome: "Finasterida Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Inibidor da 5-alfa-redutase / Urológico / Dermatológico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 75,
    descricao: "Inibidor da 5-alfa-redutase para hiperplasia prostática benigna e alopecia androgênica.",
  },
  {
    slug: "tamsulosina",
    principioAtivo: "Cloridrato de Tansulosina",
    referencia: "Secotex",
    fabricanteReferencia: "Boehringer Ingelheim",
    genericos: [
      { nome: "Tansulosina EMS", fabricante: "EMS" },
      { nome: "Tansulosina Medley", fabricante: "Medley" },
      { nome: "Tansulosina Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Alfa-bloqueador Seletivo / Urológico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 68,
    descricao: "Alfa-1 bloqueador seletivo para alívio dos sintomas urinários na hiperplasia prostática benigna.",
  },
  {
    slug: "sildenafila",
    principioAtivo: "Citrato de Sildenafila",
    referencia: "Viagra",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Sildenafila EMS", fabricante: "EMS" },
      { nome: "Sildenafila Medley", fabricante: "Medley" },
      { nome: "Sildenafila Eurofarma", fabricante: "Eurofarma" },
      { nome: "Sildenafila Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Inibidor da PDE-5 / Disfunção Erétil",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 82,
    descricao: "Inibidor da fosfodiesterase 5 para tratamento da disfunção erétil e hipertensão pulmonar.",
  },
  {
    slug: "tadalafila",
    principioAtivo: "Tadalafila",
    referencia: "Cialis",
    fabricanteReferencia: "Lilly",
    genericos: [
      { nome: "Tadalafila EMS", fabricante: "EMS" },
      { nome: "Tadalafila Medley", fabricante: "Medley" },
      { nome: "Tadalafila Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Inibidor da PDE-5 / Disfunção Erétil",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 80,
    descricao: "Inibidor da PDE-5 de longa duração (até 36h) para disfunção erétil e HPB.",
  },
  {
    slug: "cianocobalamina",
    principioAtivo: "Cianocobalamina (Vitamina B12)",
    referencia: "Rubranova",
    fabricanteReferencia: "Cristália",
    genericos: [
      { nome: "Cianocobalamina EMS", fabricante: "EMS" },
      { nome: "Cianocobalamina Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Vitamina B12 / Suplementação",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 50,
    descricao: "Vitamina B12 para deficiências nutricionais, anemia megaloblástica e neuropatias.",
  },
  {
    slug: "acido-folico",
    principioAtivo: "Ácido Fólico (Vitamina B9)",
    referencia: "Folacin",
    fabricanteReferencia: "Eurofarma",
    genericos: [
      { nome: "Ácido Fólico EMS", fabricante: "EMS" },
      { nome: "Ácido Fólico Medley", fabricante: "Medley" },
      { nome: "Ácido Fólico Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Vitamina B9 / Suplementação",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 52,
    descricao: "Vitamina B9 essencial na gestação para prevenção de defeitos do tubo neural.",
  },
  {
    slug: "sulfato-ferroso",
    principioAtivo: "Sulfato Ferroso",
    referencia: "Noripurum Oral",
    fabricanteReferencia: "Vifor Pharma",
    genericos: [
      { nome: "Sulfato Ferroso EMS", fabricante: "EMS" },
      { nome: "Sulfato Ferroso Medley", fabricante: "Medley" },
      { nome: "Sulfato Ferroso Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Suplemento de Ferro / Antianêmico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 58,
    descricao: "Suplementação de ferro para prevenção e tratamento da anemia ferropriva.",
  },
  {
    slug: "colecalciferol",
    principioAtivo: "Colecalciferol (Vitamina D3)",
    referencia: "Depura",
    fabricanteReferencia: "Mantecorp",
    genericos: [
      { nome: "Colecalciferol EMS", fabricante: "EMS" },
      { nome: "Colecalciferol Medley", fabricante: "Medley" },
      { nome: "Colecalciferol Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Vitamina D / Suplementação",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 55,
    descricao: "Vitamina D3 para prevenção e tratamento de deficiência de vitamina D e raquitismo.",
  },
  {
    slug: "hidroxicloroquina",
    principioAtivo: "Sulfato de Hidroxicloroquina",
    referencia: "Reuquinol",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Hidroxicloroquina EMS", fabricante: "EMS" },
      { nome: "Hidroxicloroquina Medley", fabricante: "Medley" },
      { nome: "Hidroxicloroquina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antimalárico / Antirreumático (DMARD)",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 60,
    descricao: "Antimalárico e DMARD para lúpus eritematoso sistêmico e artrite reumatoide.",
  },
  {
    slug: "metotrexato",
    principioAtivo: "Metotrexato",
    referencia: "Methofar / Tecnomet",
    fabricanteReferencia: "Zodiac / Cristália",
    genericos: [
      { nome: "Metotrexato EMS", fabricante: "EMS" },
      { nome: "Metotrexato Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Antirreumático (DMARD) / Imunossupressor",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 57,
    descricao: "DMARD imunossupressor para artrite reumatoide, psoríase e doenças autoimunes.",
  },
  {
    slug: "colchicina",
    principioAtivo: "Colchicina",
    referencia: "Colchimed",
    fabricanteReferencia: "Sigma Pharma",
    genericos: [
      { nome: "Colchicina EMS", fabricante: "EMS" },
      { nome: "Colchicina Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antigotoso / Anti-inflamatório",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 54,
    descricao: "Anti-inflamatório específico para crises de gota aguda e pericardite.",
  },
  {
    slug: "aciclovir",
    principioAtivo: "Aciclovir",
    referencia: "Zovirax",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Aciclovir EMS", fabricante: "EMS" },
      { nome: "Aciclovir Medley", fabricante: "Medley" },
      { nome: "Aciclovir Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Antiviral",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 65,
    descricao: "Antiviral para herpes simples, herpes-zóster e varicela.",
  },
  {
    slug: "oseltamivir",
    principioAtivo: "Fosfato de Oseltamivir",
    referencia: "Tamiflu",
    fabricanteReferencia: "Roche",
    genericos: [
      { nome: "Oseltamivir EMS", fabricante: "EMS" },
      { nome: "Oseltamivir Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antiviral / Influenza",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 45,
    descricao: "Antiviral inibidor da neuraminidase para tratamento e profilaxia da influenza.",
  },
  {
    slug: "nitrazepam",
    principioAtivo: "Nitrazepam",
    referencia: "Sonebon",
    fabricanteReferencia: "Boehringer Ingelheim",
    genericos: [
      { nome: "Nitrazepam EMS", fabricante: "EMS" },
      { nome: "Nitrazepam Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Benzodiazepínico / Hipnótico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 56,
    descricao: "Hipnótico benzodiazepínico para insônia e espasmos infantis.",
  },
  {
    slug: "beclometasona",
    principioAtivo: "Dipropionato de Beclometasona",
    referencia: "Clenil",
    fabricanteReferencia: "Chiesi",
    genericos: [
      { nome: "Beclometasona EMS", fabricante: "EMS" },
      { nome: "Beclometasona Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Corticosteroide Inalatório",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 48,
    descricao: "Corticosteroide inalatório de baixo a médio custo para controle da asma.",
  },
  {
    slug: "formoterol",
    principioAtivo: "Fumarato de Formoterol",
    referencia: "Foradil",
    fabricanteReferencia: "Novartis",
    genericos: [
      { nome: "Formoterol EMS", fabricante: "EMS" },
      { nome: "Formoterol Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Broncodilatador / Beta-2 agonista de Longa Ação",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 50,
    descricao: "Beta-2 agonista de longa ação (LABA) para controle da asma e DPOC.",
  },
  {
    slug: "ipratropio",
    principioAtivo: "Brometo de Ipratrópio",
    referencia: "Atrovent",
    fabricanteReferencia: "Boehringer Ingelheim",
    genericos: [
      { nome: "Ipratrópio EMS", fabricante: "EMS" },
      { nome: "Ipratrópio Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Broncodilatador Anticolinérgico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 47,
    descricao: "Broncodilatador anticolinérgico de ação curta para DPOC e asma.",
  },
  {
    slug: "espironolactona-25mg",
    principioAtivo: "Espironolactona 25mg",
    referencia: "Aldactone 25mg",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Espironolactona 25mg EMS", fabricante: "EMS" },
      { nome: "Espironolactona 25mg Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Diurético Poupador de Potássio",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 64,
    descricao: "Dose baixa de espironolactona para insuficiência cardíaca e hirsutismo feminino.",
  },
  {
    slug: "clortalidona",
    principioAtivo: "Clortalidona",
    referencia: "Higroton",
    fabricanteReferencia: "Novartis",
    genericos: [
      { nome: "Clortalidona EMS", fabricante: "EMS" },
      { nome: "Clortalidona Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Diurético Tiazídico",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 68,
    descricao: "Diurético tiazídico de longa ação para hipertensão arterial e edema.",
  },
  {
    slug: "lisinopril",
    principioAtivo: "Lisinopril",
    referencia: "Zestril / Prinivil",
    fabricanteReferencia: "AstraZeneca / MSD",
    genericos: [
      { nome: "Lisinopril EMS", fabricante: "EMS" },
      { nome: "Lisinopril Medley", fabricante: "Medley" },
      { nome: "Lisinopril Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Anti-hipertensivo / IECA",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 73,
    descricao: "IECA de longa ação para hipertensão, insuficiência cardíaca e nefropatia diabética.",
  },
  {
    slug: "ramipril",
    principioAtivo: "Ramipril",
    referencia: "Triatec",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Ramipril EMS", fabricante: "EMS" },
      { nome: "Ramipril Medley", fabricante: "Medley" },
      { nome: "Ramipril Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Anti-hipertensivo / IECA",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 70,
    descricao: "IECA com proteção cardiovascular e renal em pacientes de alto risco.",
  },
  {
    slug: "valsartana",
    principioAtivo: "Valsartana",
    referencia: "Diovan",
    fabricanteReferencia: "Novartis",
    genericos: [
      { nome: "Valsartana EMS", fabricante: "EMS" },
      { nome: "Valsartana Medley", fabricante: "Medley" },
      { nome: "Valsartana Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Anti-hipertensivo / ARA II",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 71,
    descricao: "ARA II para hipertensão arterial e insuficiência cardíaca pós-infarto.",
  },
  {
    slug: "irbesartana",
    principioAtivo: "Irbesartana",
    referencia: "Aprovel",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Irbesartana EMS", fabricante: "EMS" },
      { nome: "Irbesartana Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Anti-hipertensivo / ARA II",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 68,
    descricao: "ARA II com proteção renal especial em pacientes diabéticos hipertensos.",
  },
  {
    slug: "telmisartana",
    principioAtivo: "Telmisartana",
    referencia: "Micardis",
    fabricanteReferencia: "Boehringer Ingelheim",
    genericos: [
      { nome: "Telmisartana EMS", fabricante: "EMS" },
      { nome: "Telmisartana Medley", fabricante: "Medley" },
      { nome: "Telmisartana Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Anti-hipertensivo / ARA II",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 72,
    descricao: "ARA II de meia-vida mais longa (24h) para hipertensão e prevenção cardiovascular.",
  },
  {
    slug: "pioglitazona",
    principioAtivo: "Cloridrato de Pioglitazona",
    referencia: "Actos",
    fabricanteReferencia: "Takeda",
    genericos: [
      { nome: "Pioglitazona EMS", fabricante: "EMS" },
      { nome: "Pioglitazona Medley", fabricante: "Medley" },
      { nome: "Pioglitazona Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antidiabético / Tiazolidinediona",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 69,
    descricao: "Sensibilizador de insulina para diabetes tipo 2, reduz resistência periférica à insulina.",
  },
  {
    slug: "glimepirida",
    principioAtivo: "Glimepirida",
    referencia: "Amaryl",
    fabricanteReferencia: "Sanofi",
    genericos: [
      { nome: "Glimepirida EMS", fabricante: "EMS" },
      { nome: "Glimepirida Medley", fabricante: "Medley" },
      { nome: "Glimepirida Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antidiabético / Sulfonilureia de 3ª Geração",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 70,
    descricao: "Sulfonilureia de terceira geração para diabetes tipo 2 com menor risco de hipoglicemia.",
  },
  {
    slug: "sitagliptina",
    principioAtivo: "Fosfato de Sitagliptina",
    referencia: "Januvia",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Sitagliptina EMS", fabricante: "EMS" },
      { nome: "Sitagliptina Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Antidiabético / Inibidor DPP-4",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 65,
    descricao: "Inibidor da DPP-4 para diabetes tipo 2, aumenta incretinas endógenas.",
  },
  {
    slug: "lamotrigina",
    principioAtivo: "Lamotrigina",
    referencia: "Lamictal",
    fabricanteReferencia: "GSK",
    genericos: [
      { nome: "Lamotrigina EMS", fabricante: "EMS" },
      { nome: "Lamotrigina Medley", fabricante: "Medley" },
      { nome: "Lamotrigina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Anticonvulsivante / Estabilizador de Humor",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 72,
    descricao: "Anticonvulsivante e estabilizador de humor para epilepsia e transtorno bipolar.",
  },
  {
    slug: "mirtazapina",
    principioAtivo: "Mirtazapina",
    referencia: "Remeron",
    fabricanteReferencia: "MSD",
    genericos: [
      { nome: "Mirtazapina EMS", fabricante: "EMS" },
      { nome: "Mirtazapina Medley", fabricante: "Medley" },
      { nome: "Mirtazapina Sandoz", fabricante: "Sandoz" },
    ],
    classeTerapeutica: "Antidepressivo NaSSA",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 68,
    descricao: "Antidepressivo noradrenérgico e serotoninérgico específico para depressão com ansiedade e insônia.",
  },
  {
    slug: "duloxetina",
    principioAtivo: "Cloridrato de Duloxetina",
    referencia: "Cymbalta",
    fabricanteReferencia: "Lilly",
    genericos: [
      { nome: "Duloxetina EMS", fabricante: "EMS" },
      { nome: "Duloxetina Medley", fabricante: "Medley" },
      { nome: "Duloxetina Eurofarma", fabricante: "Eurofarma" },
    ],
    classeTerapeutica: "Antidepressivo / IRSN",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 73,
    descricao: "IRSN indicado para depressão, ansiedade generalizada, dor neuropática e fibromialgia.",
  },
  {
    slug: "trazodona",
    principioAtivo: "Cloridrato de Trazodona",
    referencia: "Donaren",
    fabricanteReferencia: "Bristol-Myers Squibb",
    genericos: [
      { nome: "Trazodona EMS", fabricante: "EMS" },
      { nome: "Trazodona Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Antidepressivo SARI",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 61,
    descricao: "Antidepressivo SARI com propriedades sedativas para depressão com insônia associada.",
  },
  {
    slug: "fenitoina",
    principioAtivo: "Fenitoína Sódica",
    referencia: "Hidantal",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Fenitoína EMS", fabricante: "EMS" },
      { nome: "Fenitoína Medley", fabricante: "Medley" },
    ],
    classeTerapeutica: "Anticonvulsivante / Hidantoína",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 63,
    descricao: "Anticonvulsivante hidantoínico para epilepsia tônico-clônica e crises parciais complexas.",
  },
  {
    slug: "carbonato-de-calcio",
    principioAtivo: "Carbonato de Cálcio",
    referencia: "Caltrate",
    fabricanteReferencia: "Pfizer",
    genericos: [
      { nome: "Carbonato de Cálcio EMS", fabricante: "EMS" },
      { nome: "Carbonato de Cálcio Medley", fabricante: "Medley" },
      { nome: "Carbonato de Cálcio Prati", fabricante: "Prati-Donaduzzi" },
    ],
    classeTerapeutica: "Suplemento de Cálcio / Antiácido",
    bioequivalenciaAnvisa: true,
    diferencaPrecoEstimada: 54,
    descricao: "Suplementação de cálcio para osteoporose, osteopenia e como antiácido.",
  },
];

export function getMedicamento(slug: string): Medicamento | undefined {
  return medicamentos.find((m) => m.slug === slug);
}

export function buscarMedicamentos(query: string): Medicamento[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return medicamentos.filter(
    (m) =>
      m.principioAtivo.toLowerCase().includes(q) ||
      m.referencia.toLowerCase().includes(q) ||
      m.classeTerapeutica.toLowerCase().includes(q) ||
      m.genericos.some((g) => g.nome.toLowerCase().includes(q))
  );
}
